# Generated by Django 5.2.12 on 2026-03-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=100.0, help_text='Default shipping cost in NPR', max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=5000.0, help_text='Order amount for free shipping in NPR', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate in percentage', max_digits=5)),
                ('currency_symbol', models.CharField(default='NPR', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
