# Generated by Django 5.2.12 on 2026-03-23 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_footercolumn_created_at_navigationmenu_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('subtitle', models.TextField(default='To build a framework that makes auto repair predictable.')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About Hero',
                'verbose_name_plural': 'About Hero',
            },
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('alt_text', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About Image',
                'verbose_name_plural': 'About Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('our_story', 'Our Story'), ('text_section', 'Text Section'), ('text_with_stats', 'Text with Statistics')], max_length=20)),
                ('label', models.CharField(blank=True, help_text="Small label above heading (e.g., 'OUR STORY')", max_length=100)),
                ('heading', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='footerlink',
            name='custom_path',
            field=models.CharField(blank=True, help_text='Optional: Custom redirect path', max_length=200),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='open_in_new_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='custom_path',
            field=models.CharField(blank=True, help_text='Optional: Custom redirect path', max_length=200),
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='open_in_new_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(help_text="URL path (e.g., '/about', '/faq', '/contact')", max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationmenu',
            name='url',
            field=models.CharField(help_text="URL path (e.g., '/about', '/shop', '/contact')", max_length=200),
        ),
        migrations.CreateModel(
            name='AboutStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="e.g., '25K+', '57K+'", max_length=20)),
                ('label', models.CharField(help_text="e.g., 'Happy Customers'", max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='cms.aboutsection')),
            ],
            options={
                'verbose_name': 'About Statistic',
                'verbose_name_plural': 'About Statistics',
                'ordering': ['order'],
            },
        ),
    ]
