# Generated by Django 5.2.12 on 2026-03-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_abouthero_aboutimage_aboutsection_contactsubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this widget', max_length=200)),
                ('widget_type', models.CharField(choices=[('hero_banner', 'Hero Banner'), ('image_banner', 'Image Banner'), ('text_section', 'Text Section'), ('text_with_label', 'Text with Label (Our Story style)'), ('text_with_stats', 'Text with Statistics'), ('single_image', 'Single Image'), ('two_column_images', 'Two Column Images'), ('image_gallery', 'Image Gallery'), ('features_grid', 'Features Grid'), ('testimonials_slider', 'Testimonials Slider'), ('vendors_showcase', 'Vendors Showcase'), ('faq_accordion', 'FAQ Accordion'), ('contact_form', 'Contact Form'), ('store_locations', 'Store Locations'), ('featured_products', 'Featured Products'), ('product_categories', 'Product Categories'), ('product_slider', 'Product Slider'), ('html_content', 'Custom HTML Content'), ('spacer', 'Spacer/Divider')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WidgetFAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='cms.widget')),
            ],
            options={
                'verbose_name': 'Widget FAQ Item',
                'verbose_name_plural': 'Widget FAQ Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WidgetHeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('background_image', models.ImageField(upload_to='widgets/hero/')),
                ('overlay_opacity', models.IntegerField(default=30, help_text='0-100')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_banner_content', to='cms.widget')),
            ],
            options={
                'verbose_name': 'Hero Banner Content',
                'verbose_name_plural': 'Hero Banner Contents',
            },
        ),
        migrations.CreateModel(
            name='WidgetHTMLContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(help_text='Custom HTML content')),
                ('css_classes', models.CharField(blank=True, help_text='Additional CSS classes', max_length=200)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='html_content', to='cms.widget')),
            ],
            options={
                'verbose_name': 'HTML Content',
                'verbose_name_plural': 'HTML Contents',
            },
        ),
        migrations.CreateModel(
            name='WidgetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='widgets/images/')),
                ('alt_text', models.CharField(max_length=200)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.widget')),
            ],
            options={
                'verbose_name': 'Widget Image',
                'verbose_name_plural': 'Widget Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WidgetStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="e.g., '25K+', '57K+'", max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='cms.widget')),
            ],
            options={
                'verbose_name': 'Widget Statistic',
                'verbose_name_plural': 'Widget Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WidgetTextSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Small label above heading', max_length=100)),
                ('heading', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=20)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_section_content', to='cms.widget')),
            ],
            options={
                'verbose_name': 'Text Section Content',
                'verbose_name_plural': 'Text Section Contents',
            },
        ),
        migrations.CreateModel(
            name='PageWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Widget-specific configuration')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_widgets', to='cms.page')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_pages', to='cms.widget')),
            ],
            options={
                'verbose_name': 'Page Widget',
                'verbose_name_plural': 'Page Widgets',
                'ordering': ['order'],
                'unique_together': {('page', 'widget', 'order')},
            },
        ),
    ]
