# Generated by Django 5.2.12 on 2026-03-25 09:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_page_widget_widgetfaqitem_widgetherobanner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='newsletter_description',
            field=ckeditor.fields.RichTextField(default="Whether you're welcoming new contacts or sharing the latest news..."),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='widgethtmlcontent',
            name='html_content',
            field=ckeditor.fields.RichTextField(help_text='Custom HTML content'),
        ),
        migrations.AlterField(
            model_name='widgettextsection',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
