# Generated by Django 5.2.12 on 2026-03-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_aboutsection_content_alter_feature_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footercolumn',
            options={'ordering': ['order'], 'verbose_name': '📑 Footer - Column', 'verbose_name_plural': '📑 Footer - Columns'},
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['order'], 'verbose_name': '📑 Footer - Link', 'verbose_name_plural': '📑 Footer - Links'},
        ),
        migrations.AlterModelOptions(
            name='navigationmenu',
            options={'ordering': ['order'], 'verbose_name': '🔗 Header - Navigation Menu', 'verbose_name_plural': '🔗 Header - Navigation Menus'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': '📄 Page Builder - Page', 'verbose_name_plural': '📄 Page Builder - Pages'},
        ),
        migrations.AlterModelOptions(
            name='pagewidget',
            options={'ordering': ['order'], 'verbose_name': '🧩 Page Builder - Page Widget', 'verbose_name_plural': '🧩 Page Builder - Page Widgets'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': '🔗 Header - Site Settings', 'verbose_name_plural': '🔗 Header - Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ['name'], 'verbose_name': '🧩 Page Builder - Widget', 'verbose_name_plural': '🧩 Page Builder - Widgets'},
        ),
        migrations.AlterModelOptions(
            name='widgetfaqitem',
            options={'ordering': ['order'], 'verbose_name': '🧩 Page Builder - Widget FAQ Item', 'verbose_name_plural': '🧩 Page Builder - Widget FAQ Items'},
        ),
        migrations.AlterModelOptions(
            name='widgetherobanner',
            options={'verbose_name': '🧩 Page Builder - Hero Banner Content', 'verbose_name_plural': '🧩 Page Builder - Hero Banner Contents'},
        ),
        migrations.AlterModelOptions(
            name='widgethtmlcontent',
            options={'verbose_name': '🧩 Page Builder - HTML Content', 'verbose_name_plural': '🧩 Page Builder - HTML Contents'},
        ),
        migrations.AlterModelOptions(
            name='widgetimage',
            options={'ordering': ['order'], 'verbose_name': '🧩 Page Builder - Widget Image', 'verbose_name_plural': '🧩 Page Builder - Widget Images'},
        ),
        migrations.AlterModelOptions(
            name='widgetstatistic',
            options={'ordering': ['order'], 'verbose_name': '🧩 Page Builder - Widget Statistic', 'verbose_name_plural': '🧩 Page Builder - Widget Statistics'},
        ),
        migrations.AlterModelOptions(
            name='widgettextsection',
            options={'verbose_name': '🧩 Page Builder - Text Section Content', 'verbose_name_plural': '🧩 Page Builder - Text Section Contents'},
        ),
    ]
