# Generated by Django 5.2.12 on 2026-03-27 09:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_footercolumn_options_alter_footerlink_options_and_more'),
        ('products', '0004_recentlyviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('dynamic_hero', '🎯 Dynamic Hero Banner (Full Control)'), ('hero_banner', 'Hero Banner (Simple)'), ('image_banner', 'Image Banner'), ('text_section', 'Text Section'), ('text_with_label', 'Text with Label (Our Story style)'), ('text_with_stats', 'Text with Statistics'), ('single_image', 'Single Image'), ('two_column_images', 'Two Column Images'), ('image_gallery', 'Image Gallery'), ('features_grid', 'Features Grid'), ('testimonials_slider', 'Testimonials Slider'), ('vendors_showcase', 'Vendors Showcase'), ('faq_accordion', 'FAQ Accordion'), ('contact_form', 'Contact Form'), ('store_locations', 'Store Locations'), ('product_section', '🛍️ Product Section (Manual Selection)'), ('featured_products', 'Featured Products (Auto)'), ('product_categories', 'Product Categories'), ('product_slider', 'Product Slider'), ('html_content', 'Custom HTML Content'), ('spacer', 'Spacer/Divider')], max_length=50),
        ),
        migrations.CreateModel(
            name='WidgetDynamicHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading', max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Description text (supports HTML)')),
                ('background_image', models.ImageField(help_text='Hero background image', upload_to='widgets/hero/')),
                ('show_discount_badge', models.BooleanField(default=False, help_text='Show discount circle badge')),
                ('discount_percentage', models.IntegerField(default=0, help_text='Discount percentage (e.g., 64)')),
                ('discount_text', ckeditor.fields.RichTextField(blank=True, help_text='Text next to discount badge')),
                ('show_button', models.BooleanField(default=True, help_text='Show call-to-action button')),
                ('button_text', models.CharField(default='Shop Now', help_text='Button text', max_length=50)),
                ('button_link', models.CharField(default='/shop', help_text='Button URL', max_length=200)),
                ('show_price', models.BooleanField(default=False, help_text='Show price section')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price to display', max_digits=10)),
                ('price_text', models.CharField(blank=True, help_text="Text below price (e.g., 'Starting from')", max_length=100)),
                ('text_color', models.CharField(default='#064C50', help_text='Text color (hex code)', max_length=20)),
                ('overlay_opacity', models.IntegerField(default=0, help_text='Background overlay opacity (0-100)')),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_hero_content', to='cms.widget')),
            ],
            options={
                'verbose_name': '🧩 Page Builder - Dynamic Hero Content',
                'verbose_name_plural': '🧩 Page Builder - Dynamic Hero Contents',
            },
        ),
        migrations.CreateModel(
            name='WidgetProductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(help_text="Section heading (e.g., 'Featured Products', 'Best Sellers')", max_length=200)),
                ('products', models.ManyToManyField(blank=True, help_text='Select up to 8 products', related_name='widget_sections', to='products.product')),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_section_content', to='cms.widget')),
            ],
            options={
                'verbose_name': '🧩 Page Builder - Product Section Content',
                'verbose_name_plural': '🧩 Page Builder - Product Section Contents',
            },
        ),
    ]
