# Generated by Django 5.2.12 on 2026-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_widget_widget_type_widgetdynamichero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetdynamichero',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Hero background image (optional)', null=True, upload_to='widgets/hero/'),
        ),
    ]
