# Generated by Django 5.2.12 on 2026-03-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('cms', '0008_alter_widgetdynamichero_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenuSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.TextField(default='Suspendisse potenti. Nam pharetra lorem eu varius commodo. Etiam a ornare ligula.', help_text='Text displayed at the bottom of the categories mega menu')),
                ('sale_badge_text', models.CharField(default='SALE', help_text='Text for the sale badge', max_length=50)),
                ('sale_badge_label', models.CharField(default='Best Seller', help_text='Label before the sale badge', max_length=100)),
                ('show_sale_badge', models.BooleanField(default=True, help_text='Show/hide the sale badge in header')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '🔗 Header - Mega Menu Settings',
                'verbose_name_plural': '🔗 Header - Mega Menu Settings',
            },
        ),
        migrations.CreateModel(
            name='MegaMenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Display order (1-9)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='megamenu_items', to='categories.category')),
            ],
            options={
                'verbose_name': '🔗 Header - Mega Menu Category',
                'verbose_name_plural': '🔗 Header - Mega Menu Categories',
                'ordering': ['order'],
            },
        ),
    ]
